version: "3"

services:
    government.agent.de4a.eu:
        container_name: ${DOMAIN}
        image: ${AGENT_REST_IMAGE}:${AGENT_REST_IMAGE_TAG}
        environment:
            - ARIESD_API_HOST=${GOV_HOST}:${GOV_API_PORT}
            - ARIESD_INBOUND_HOST=${HTTP_SCHEME}@${GOV_HOST}:${GOV_INBOUND_PORT}
            - ARIESD_INBOUND_HOST_EXTERNAL=${HTTP_SCHEME}@http://${DOMAIN}:${GOV_INBOUND_PORT}
            - ARIESD_WEBHOOK_URL=http://${GOV_WEBHOOK_CONTAINER_NAME}:${GOV_WEBHOOK_PORT}
            - ARIESD_DEFAULT_LABEL=goverment-agent
            - ARIESD_AUTO_ACCEPT=true
            - ARIESD_DATABASE_TYPE=leveldb
            - ARIESD_DATABASE_PREFIX=goverment
            - ARIESD_DATABASE_TIMEOUT=60
            - ARIESD_HTTP_RESOLVER=${HTTP_DID_RESOLVER}
            #- TLS_CERT_FILE=/etc/tls/ec-pubCert.pem
            #- TLS_KEY_FILE=/etc/tls/ec-key.pem
            # volumes:
            # - ./keys/tls:/etc/tls
        ports:
            - ${GOV_INBOUND_PORT}:${GOV_INBOUND_PORT}
            - ${GOV_API_PORT}:${GOV_API_PORT}
        entrypoint: ""
        # command: /bin/sh -c "cp /etc/tls/* /usr/local/share/ca-certificates/;update-ca-certificates; aries-agent-rest start"
        command: /bin/sh -c "aries-agent-rest start"
        networks:
            - bdd_net

    government.webhook.de4a.eu:
        container_name: ${GOV_WEBHOOK_CONTAINER_NAME}
        image: ${SAMPLE_WEBHOOK_IMAGE}:${SAMPLE_WEBHOOK_IMAGE_TAG}
        environment:
            - WEBHOOK_PORT=${GOV_WEBHOOK_PORT}
        ports:
            - ${GOV_WEBHOOK_PORT}:${GOV_WEBHOOK_PORT}
        networks:
            - bdd_net

    couchdb.de4a.eu:
        container_name: couchdb.de4a.eu
        image: ${COUCHDB_IMAGE}:${COUCHDB_IMAGE_TAG}
        ports:
            - ${COUCHDB_PORT}:${COUCHDB_PORT}
        environment:
            - COUCHDB_USER=${COUCHDB_USER}
            - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
        volumes:
            - ./couchdb-config/10-single-node.ini:/opt/couchdb/etc/local.d/10-single-node.ini
            - ${COUCHDB_PATH}:/opt/couchdb/data
        networks:
            - bdd_net

    government.agent.api.de4a.eu:
        container_name: ${AGENT_API_CONTAINER_NAME}
        image: ${AGENT_API_IMAGE}:${AGENT_API_IMAGE_TAG}
        ports:
            - 0.0.0.0:${AGENT_API_PORT}:8080
        volumes:
            - ./api-java/jars/DE4AEBSIConnector-0.1-launcher.jar:/usr/local/tomcat/webapps/DE4AEBSIConnector-0.1-launcher.jar
            - ./api-java/webapps/de4a-agent.war:/usr/local/tomcat/webapps/de4a-agent.war
            - ./api-java/conf/web.xml:/usr/local/tomcat/conf/web.xml
            - ./api-java/conf/app.properties:/usr/local/tomcat/conf/app.properties
        networks:
            - bdd_net
volumes:
    db_data: {}

networks:
    bdd_net:
        driver: bridge
