openapi: 3.0.0
info:
  title: DE4A Authority Agent
  version: 0.0.1
servers:
  - url: 'http://164.8.250.43:8080/de4a-agent/v1'
tags:
   
  - name: DID connection
    description: Operations for managing the DID connections and invitations sent by the Authority Agent.
  - name: verifiable credentials
    description: Operations for managing verifiable credentials on the DP/DC side.
  - name: offer
    description: Operations for managing VC offers sent by the Authority Agent.
  - name: verifiable presentations
    description: Operations for managing verifiable presentations to be submitted by the student on the DC side.
    
paths:
  /generate-invitation:
    post:
      tags:
        - DID connection
      summary: Generate DID invitation for establishing a DID communication between the Authority Agent and the student's Edge Agent.
      requestBody:
        description: The user data obtained from the eProcedure Portal.
        required: true
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/UserData'
      responses:
        '200':
          description: The DID invitation JSON value based on which a QR code on the eProcedure Portal should be generated.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Invitation'
              example:
                  {"serviceEndpoint":"http://alice.aries.example.com:8081","recipientKeys":["did:key:z6MkeUtPN4jBEJ97PrGV5EtgqM9KfbWoFNxeXzHLSEz4EJAp"],"@id":"af62fe2f-d554-46dc-8700-1d92813abab4","label":"alice-agent","@type":"https://didcomm.org/didexchange/1.0/invitation"}
  /did-conn-status/{userId}:
    get:
      tags:
        - DID connection
      summary: Retrieve the current status of the DID connection between the Authority Agent and the student's Edge Agent.
      parameters:
          - in: path
            name: userId
            required: true
            schema:
              type: string
            description: The user ID included in the eIDAS minimum dataset for the identificaton of a natural person. The value is obtained from the eProcedure Portal.
      responses:
        '200':
          description: The connection has already been established.
          content:
            application/json:
              schema:
                type: integer
                example: 1
        '300':
          description: The invitation has been generated, but there is still no response from the student.
          content:
            application/json:
              schema:
                type: integer   
                example: 0
        '400':
          description: The invitation has never been generated. 
          content:
            application/json:
              schema:
                type: integer
                example: -1
  /send-vc-offer:
    post:
      tags:
        - offer
      summary: Generate and send a VC offer to the student's Edge Agent for the student to accept before sending him/her the diploma evidence as a VC.
      requestBody:
        description:  An object including the user ID obtained from eIDAS minimum dataset for the identificaton of a natural person and the diploma evidence in the canonical XML format, which is to be convert to VC JSON-LD format and digitally signed by using the issuer's DID.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OfferData'
      
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
                example: true
       
        '404':
          description: FAILED
          content:
            application/json:
              schema:
                type: boolean
                example: false      
  /generate-vc:
    post:
      tags:
        - verifiable credentials
      summary: Generate and sign a verifiable credential for a given student based on the input evidence.
      requestBody:
        description:  An object including information about the DIDs of the Authority Agent deployed on the Data Owner side (myDID) and the student's Edge Agent (theirDID), the DID identifier of the DO Authority Agent optionally registered in the EBSI DID registry (TIR) and the diploma evidence in the canonical XML format.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VCData'
      responses:
        '200':
            description: Successfully generated verifiable credential for the student.
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/VerifiableCredential'
                  example: {}
        '404':
            description: FAILED
            content:
              application/json:
                  schema:
                    $ref: '#/components/schemas/Error'
                    example: {}
                  
  
  /check-offer-vc-response/{userId}:
    get:
      tags:
        - verifiable credentials
      summary: Check the current status of the student's response to the VC or offer sent by the Authority Agent.
      parameters:
          - in: path
            name: userId
            required: true
            schema:
               type: string
            description: The user ID included in the eIDAS minimum dataset for the identificaton of a natural person. The value is obtained from the eProcedure Portal.
      responses:
        '200':
          description: The VC has been accepted by the student.
          content:
            application/json:
              schema:
                type: integer
                example: 5
        '301':                                                      
          description: The VC has been sent to the student, but has not yet been accepted.
          content:
            application/json:
              schema:
                type: integer
                example: 2  
        '302':
          description: The offer has been accepted by the student, but the VC was never sent.
          content:
            application/json:
              schema:
                type: integer
                example: -3 
        '303':
          description: The offer has been accepted by the student.
          content:
            application/json:
              schema:
                type: integer
                example: 1 
        '401':                                                      
          description: The offer has been sent to the student, but has not yet been accepted.
          content:
            application/json:
              schema:
                type: integer
                example: 0  
        '402':
          description: The offer has not been sent to the student.
          content:
            application/json:
              schema:
                type: integer
                example: -1
        '501':
          description: The offer has been rejected by the student.
          content:
            application/json:
              schema:
                type: integer
                example: -2   
        '502':
          description: The VC has been rejected by the student.
          content:
            application/json:
              schema:
                type: integer
                example: -4 
                
  /send-vc/:
    post:
      tags:
        - verifiable credentials
      summary: Send a digitally signed verifiable credential to the student after the offer was accepted.
      requestBody:
        description:  The user data obtained from the eProcedure Portal.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserData'
        
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
                example: true
       
        '404':
          description: FAILED
          content:
            application/json:
              schema:
                type: boolean
                example: false
        
  /send-vp-request:
    post:
      tags:
        - verifiable presentations
      summary: Request the student to submit a verifiable presentation (VP) in a given format.
      requestBody:
        description:  The data object including the user ID from the eIDAS minimum dataset for the identificaton of a natural person (the value obtained from the eProcedure Portal) and the requested format of the VP.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VPRequestData'
     
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '404':
          description: FAILED
          content:
            application/json:
              schema:
                type: boolean
                example: false     
   
  /check-request-vp-response/{userId}:
    get:
      tags:
        - verifiable presentations
      summary: Retrieve the current status of the VP submission or request for VP.
      parameters:
          - in: path
            name: userId
            required: true
            schema:
               type: string
            description: The user ID included in the eIDAS minimum dataset for the identificaton of a natural person. The value is obtained from the eProcedure Portal.
      responses:
        '200':
          description: The VP has been received.
          content:
            application/json:
              schema:
                type: integer
                example: 1
        '301':                                                      
          description: The VP request has been sent to the student, but has not yet been accepted.
          content:
            application/json:
              schema:
                type: integer
                example: 0  
        '401':
          description: The VP request has not been sent to the student.
          content:
            application/json:
              schema:
                type: integer
                example: -1
        '402':
          description: The VP request has been rejected by the student.
          content:
            application/json:
              schema:
                type: integer
                example: -2   
         
  /validate-vp/{userId}:
    post:
      tags:
        - verifiable presentations
      summary: Validate the validity of the submitted verifiable presentation with regards to its schema structure, eIDAS identification and digital signature.
      parameters:
          - in: path
            name: userId
            required: true
            schema:
              type: string
            description: The user ID of the student.
      requestBody:
        description:  The data object representing the eIDAS minimum dataset for the identificaton of a natural person (the value obtained from the eProcedure Portal).
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EIDASData'
          
      responses:
        '200':
          description: An object containing the results of the validation of each VP element
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchemaValidation'
                
        '404':
          description: Empty object
          content:
            application/json:
              schema:
                example: {}     
   
         
            
             
components:
  schemas:
    UserData:
      type: object
      properties:
        userId: 
          type: string
          description: The user ID included in the eIDAS minimum dataset for the identificaton of a natural person. The value is obtained from the eProcedure Portal.
    
    EIDASData:
      type: object
      properties:
        userId: 
          type: string
          description: The natural person identifier.
        birthName:
          type: string
          description: The firstname of a person.
        givenName:
          type: string
          description: The lastname of a person.
          
    Invitation:
      type: object
      properties:
        id:
          type: string
        serviceEndpoint: 
          type: string
        recipientKeys: 
          type: array
          items: 
            type: string
        label: 
          type: string
        type:
          type: string
          
    OfferData:
      type: object
      properties:
        userId:
            type: string
            description: The user ID included in the eIDAS minimum dataset for the identificaton of a natural person. The value is obtained from the eProcedure Portal.
        evidence:
            type: string
            
    VCData:
      type: object
      properties:
        myDID:
          type: string
          description: The DID of the Authority Agent deployed on the Data Owner side.
        theirDID:
          type: string
          description: The DID identifier of the student's Edge Agent.
        publicDID:
          type: string
          description: The DID identifier of the DO Authority Agent, which is optionally registered in the EBSI DID registry (TIR).
        evidence:
          type: string
          description: The diploma evidence in the canonical XML format, which is to be converted to VC JSON-LD format and digitally signed by using the issuer's public DID.
          
    VPRequestData:
      type: object
      properties:
        userId:
            type: string
            description: The user ID included in the eIDAS minimum dataset for the identificaton of a natural person. The value is obtained from the eProcedure Portal.
        presentationFormat:
              type: string
              description: The requested format of the VP.
          
    Person:
      type: object
      properties:
            id: 
              type: string
            fullName:
              type: string
            achievements:
              type: array
              items:
                type: object
            activities:
              type: array
              items: 
                type: object
    Evidence:
      type: object
      properties:
        credentialSubject: 
          type: object
          $ref: '#/components/schemas/Person'
  
    VerifiableCredential:
      type: object
      $ref: '#/components/schemas/Evidence' 
      
    SchemaValidation:
      type: object
      properties:
          subjectCheck: 
            type: integer
          schemaCheck:
            type: integer
          issuerCheck:
            type: integer
      
    Error:
      type: object
      properties:
        code:
          type: string
        description: 
          type: string
